apiVersion: v2
name: argo-seed-infra
description: A Helm chart to deploy argocd seed project and application.
type: application
version: 0.1.0
appVersion: "1.0.0"
icon: http://null
dependencies:
  - name: argo-projs
    repository: file://./helm-charts/argo-projs/
    version: 0.1.0
    alias: seedProject
    condition: seedProject.enabled
  - name: argo-apps
    repository: file://./helm-charts/argo-apps/
    version: 0.1.0
    alias: projects
    condition: projects.enabled
  - name: argo-apps
    repository: file://./helm-charts/argo-apps/
    version: 0.1.0
    alias: applications
    condition: applications.enabled
