{{- $namespace := ternary .Values.namespace.name .Values.namespace.existingNamespace ( eq .Values.namespace.existingNamespace "" ) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.project.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.project.name }}
    namespace: {{ $namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.project.name }}
  apiGroup: rbac.authorization.k8s.io