apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  destination:
    namespace: {{ .Values.destination.namespace }}
    server: {{ .Values.destination.server }}
  project: {{ .Values.project.name }}
  source:
  {{- if .Values.chart }}
    chart: {{ .Values.chart }}
  {{- end }}
    helm:
    {{- if .Values.chart }}
      releaseName: {{ .Values.releaseName }}
    {{- if .Values.parameters }}
      parameters:
      {{- range $k, $v := .Values.parameters }}
        - name: {{ $v.name }}
          value: {{ $v.values }}
      {{- end }}
    {{- end }}
    {{- if .Values.valuesObjects }}
      valuesObject:
      {{- toYaml .Values.valuesObjects | nindent 8 }}
    {{- end }}
    {{- if .Values.values }}
      values: |
      {{- .Values.values | nindent 8 }}
    {{- end }}
    {{- end }}
    {{- if .Values.valueFiles }}
      valueFiles:
        {{- range $k, $v := .Values.valueFiles }}
        - {{ $v }}
        {{- end }}
    {{- end }}
  {{- if not ( .Values.chart ) }}
    path: {{ .Values.path }}
  {{- end }}
    repoURL: {{ .Values.repoUrl }}
    targetRevision: {{ .Values.targetRevision }}
  syncPolicy:
    automated:
      selfHeal: {{ .Values.selfHeal }}
    syncOptions:
    {{- range $k, $v := .Values.syncOptions }}
        - {{ $v }}
    {{- end }}