{{- if not ( .Values.repoSecret.existingSecret ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    argocd.argoproj.io/secret-type: repo-creds
data:
  url: {{ .Values.repoSecret.data.url | b64enc }}
  type: {{ .Values.repoSecret.data.type | b64enc }}
  insecure: {{ .Values.repoSecret.data.insecure | quote | b64enc }}
  sshPrivateKey: {{ .Values.repoSecret.data.sshPrivateKey | b64enc }}
{{- end }}